version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080